apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-frontend
  namespace: monitoring
  labels:
    app: grafana-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-frontend
  template:
    metadata:
      labels:
        app: grafana-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"